#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/py_daemon
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/py_daemon tox.ini requirements.txt test_requirements.txt setup.py
else
  echo "DEV_BASE is not defined"
fi
